### ISSUE TITLE
missing lock transaction on mainnet?

### ISSUE THREAD

**Issue by ccarfi** [ManyRios/unlock-dashboard#1]
Hi ManyRios- 

Am trying to find this contract / lock in the Unlock Dashboard, but can't seem to find it:
https://etherscan.io/address/0xc1EE1D6956416B46302767410c7C2efc06104859

Even when looking at a very simple query
SELECT "newLockAddress" AS lock FROM unlock."Unlock_evt_NewLock"

I don't see that contract in there.

It's a UDT lock (for a Dinner DAO), but can't seem to find it in the dashboard history.

Any ideas?

**Comment by ManyRios** [comment]
Hi @ccarfi , usually Dune analytics does maintenance on their DBs, in fact right now it is not showing the deployed locks in their entirety.

At the moment it shows 70 when clearly there are many more.

I have this result with this query: 
![image](https://user-images.githubusercontent.com/34518489/138640624-87c48265-9e56-4e77-bbb4-e4f95ff5761e.png)

![image](https://user-images.githubusercontent.com/34518489/138640695-5e472e1a-1a15-457c-8273-d6a6b134f645.png)

**Comment by ccarfi** [comment]
Although that lock shows up correctly in the "Unlock_evt_NewLock" table, it seems that lock doesn't show up at all in the "PublicLock_evt_Transfer" table.

```
SELECT "contract_address","to", "evt_block_time" FROM unlock."PublicLock_evt_Transfer"
WHERE "contract_address" = '\xc1EE1D6956416B46302767410c7C2efc06104859' or "to" = '\xc1EE1D6956416B46302767410c7C2efc06104859'
```

<img width="995" alt="Screen Shot 2021-10-25 at 8 35 45 AM" src="https://user-images.githubusercontent.com/214760/138726560-9ddb340f-bfab-4dae-b859-819818f9d60f.png">

Am I missing something?

**Comment by ManyRios** [comment]
"PublicLock_evt_transfer"  interacts with other contract address
